include:
  - project: library/ci-templates
    ref: v1.2
    file: /docker-image.yml
  - project: library/ci-templates
    ref: v1.2
    file: /jobs/test-python.yml

lint_python:
  extends: .python-lint
