stages:
  - build
  - push
  - scan
  - code_quality
  - safety
  - sign

variables:
  AFTER_SCRIPT_IGNORE_ERRORS: "true"
  IMAGE_NAME: $HARBOR_HOST/library/$CI_PROJECT_NAME

build:
  image: docker:27
  stage: build
  script:
    - docker buildx build -t $IMAGE_NAME:$CI_COMMIT_REF_SLUG .
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH

trivy_scan:
  stage: scan
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  script:
    - trivy image --exit-code 1 --ignore-unfixed --severity HIGH,CRITICAL $IMAGE_NAME:$CI_COMMIT_REF_SLUG
  allow_failure: true
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH

code_quality:
  stage: code_quality
  image: python:3.13
  before_script:
    - pip install flake8
  script:
    - flake8 .
  allow_failure: true
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH

safety:
  stage: safety
  image: python:3.13
  before_script:
    - pip install safety
  script:
    - safety check
  allow_failure: true
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH

push:
  stage: push
  image: docker:27
  script:
    - docker login -u $HARBOR_USERNAME -p $HARBOR_PASSWORD $HARBOR_HOST
    - docker buildx build --platform linux/amd64,linux/arm64
        -t $IMAGE_NAME:$CI_COMMIT_REF_SLUG
        -t $IMAGE_NAME:latest
        --cache-from type=registry,ref=$IMAGE_NAME:buildcache
        --cache-to type=registry,ref=$IMAGE_NAME:buildcache,mode=max
        --push .
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

sign:
  stage: sign
  image: bitnami/cosign:latest
  script:
    - cosign login -u $HARBOR_USERNAME -p $HARBOR_PASSWORD $HARBOR_HOST
    - cosign sign --yes --new-bundle-format=false --use-signing-config=false --key $COSIGN_PRIVATE_KEY $IMAGE_NAME:$CI_COMMIT_REF_SLUG
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
